// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GridScrollMap","status":false,"description":"マップの画面単位スクロールプラグイン","parameters":{}},
{"name":"MKR_PlayerSensor","status":true,"description":"(v2.2.7) プレイヤー探索プラグイン","parameters":{"Default_Sensor_Switch":"D","Default_Both_Sensor":"OFF","Default_Range_Visible":"ON","Default_Terrain_Decision":"ON","Default_Range_Color":"white","Default_Range_Opacity":"80","Default_Auto_Sensor":"OFF","Default_Event_Decision":"OFF","Default_Region_Decision01":"1"}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.1) 指定された番号のスイッチがONの間、\r\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"100"}}
];
