// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GridScrollMap","status":false,"description":"マップの画面単位スクロールプラグイン","parameters":{}},
{"name":"MKR_PlayerSensor","status":true,"description":"(v2.2.7) プレイヤー探索プラグイン","parameters":{"Default_Sensor_Switch":"D","Default_Both_Sensor":"OFF","Default_Range_Visible":"ON","Default_Terrain_Decision":"ON","Default_Range_Color":"white","Default_Range_Opacity":"80","Default_Auto_Sensor":"OFF","Default_Event_Decision":"OFF","Default_Region_Decision01":"1"}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.1) 指定された番号のスイッチがONの間、\r\nプレイヤー操作によるキャラの移動を禁止します。","parameters":{"Default_Move_Flag":"100"}},
{"name":"MoveAWSD","status":true,"description":"AWSDキーで移動可能にするプラグインです。","parameters":{}},
{"name":"MapNameinSaveData","status":true,"description":"セーブデータ上に現在マップ名を載せるプラグイン","parameters":{}},
{"name":"UCHU_MobileOperation","status":true,"description":"スマホ操作用プラグイン。横持ち/縦持ちに対応した仮想ボタン、\r\nタッチ操作の方法を追加拡張し、スマホプレイを快適にします。","parameters":{"---PC Option---":"","PC BtnDisplay":"false","PC TouchExtend":"true","---File Path---":"","DPad Image":"./img/system/DirPad.png","ActionBtn Image":"./img/system/ActionButton.png","CancelBtn Image":"./img/system/CancelButton.png","---Button Customize---":"","Button Opacity":"0.7","Vertical BtnZoom":"1.7","Tablet BtnZoom":"0.8","TabVertical BtnZoom":"1.1","HideButton OnMessage":"true","DPad Visible":"true","DPad Size":"200","DPad Margin":"10; 10","DPad Orientation":"left; bottom","DPad OpelationRange":"1.3","DPad DiagonalRange":"0.3","ActionBtn Visible":"true","ActionBtn Size":"100","ActionBtn Margin":"10; 90","ActionBtn Orientation":"right; bottom","CancelBtn Visible":"true","CancelBtn Size":"100","CancelBtn Margin":"110; 10","CancelBtn Orientation":"right; bottom","---TouchInput Extend---":"","Flick PageUp-PageDown":"true","HoldCanvas ActionBtn":"true","OutCanvas CancelBtn":"false","OutCanvas ActionBtn":"false","--!need AnalogMove.js!--":"","Analog Move":"false","Analog Sensitivity":"1.8"}}
];
